// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKdL12kyDezLfPJV-7XjyRwiE22zfOPnM',
    appId: '1:172818019052:web:4703377dc53fd880192bc9',
    messagingSenderId: '172818019052',
    projectId: 'film-flow-30d16',
    authDomain: 'film-flow-30d16.firebaseapp.com',
    storageBucket: 'film-flow-30d16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqiuT79Ct0fkiI2PjdfVkn5FA80VitovA',
    appId: '1:172818019052:android:fd46d4af5d4ea644192bc9',
    messagingSenderId: '172818019052',
    projectId: 'film-flow-30d16',
    storageBucket: 'film-flow-30d16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvBJGQCJEJEGEvHom_GkBHKbGJSxjUIxY',
    appId: '1:172818019052:ios:7d0d6982b7af8686192bc9',
    messagingSenderId: '172818019052',
    projectId: 'film-flow-30d16',
    storageBucket: 'film-flow-30d16.appspot.com',
    iosBundleId: 'com.example.filmflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvBJGQCJEJEGEvHom_GkBHKbGJSxjUIxY',
    appId: '1:172818019052:ios:7d0d6982b7af8686192bc9',
    messagingSenderId: '172818019052',
    projectId: 'film-flow-30d16',
    storageBucket: 'film-flow-30d16.appspot.com',
    iosBundleId: 'com.example.filmflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKdL12kyDezLfPJV-7XjyRwiE22zfOPnM',
    appId: '1:172818019052:web:961a14c479bf7dc6192bc9',
    messagingSenderId: '172818019052',
    projectId: 'film-flow-30d16',
    authDomain: 'film-flow-30d16.firebaseapp.com',
    storageBucket: 'film-flow-30d16.appspot.com',
  );
}
